name: apmcm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - openpyxl
  - xlrd
  - xgboost
  - shap
  - joblib
  - jinja2
  - notebook
  - jupyter
  - ipykernel
  - pip
