name: mcm
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas=3.0.2
  - openpyxl=3.1.5
  - xlrd=2.0.2
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - shap
  - jupyter
  - ipykernel
